// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _dispositivos from './dispositivos.bones.json'
import _inicio_dispositivos from './inicio-dispositivos.bones.json'
import _inicio_gestos from './inicio-gestos.bones.json'
import _inicio_acciones from './inicio-acciones.bones.json'
import _inicio_casas from './inicio-casas.bones.json'
import _inicio_activos from './inicio-activos.bones.json'
import _inicio_dis_conectados from './inicio-dis-conectados.bones.json'
import _inicio_ges_vin from './inicio-ges-vin.bones.json'
import _inicio_consumo from './inicio-consumo.bones.json'
import _inicio_historico from './inicio-historico.bones.json'
import _barra_casas from './barra-casas.bones.json'
import _seleccionada_casas from './seleccionada-casas.bones.json'
import _gestos from './gestos.bones.json'
import _historial from './historial.bones.json'
import _ajustes from './ajustes.bones.json'
import _cuenta from './cuenta.bones.json'
import _casas from './casas.bones.json'
import _control from './control.bones.json'
import _inicio_seccion_1 from './inicio-seccion-1.bones.json'
import _inicio_seccion_2 from './inicio-seccion-2.bones.json'
import _inicio_seccion_3 from './inicio-seccion-3.bones.json'
import _inicio from './inicio.bones.json'
import _seccion_2 from './seccion-2.bones.json'
import _seccion_3 from './seccion-3.bones.json'

registerBones({
  "dispositivos": _dispositivos,
  "inicio-dispositivos": _inicio_dispositivos,
  "inicio-gestos": _inicio_gestos,
  "inicio-acciones": _inicio_acciones,
  "inicio-casas": _inicio_casas,
  "inicio-activos": _inicio_activos,
  "inicio-dis-conectados": _inicio_dis_conectados,
  "inicio-ges-vin": _inicio_ges_vin,
  "inicio-consumo": _inicio_consumo,
  "inicio-historico": _inicio_historico,
  "barra-casas": _barra_casas,
  "seleccionada-casas": _seleccionada_casas,
  "gestos": _gestos,
  "historial": _historial,
  "ajustes": _ajustes,
  "cuenta": _cuenta,
  "casas": _casas,
  "control": _control,
  "inicio-seccion-1": _inicio_seccion_1,
  "inicio-seccion-2": _inicio_seccion_2,
  "inicio-seccion-3": _inicio_seccion_3,
  "inicio": _inicio,
  "seccion-2": _seccion_2,
  "seccion-3": _seccion_3,
})
